// Inlines src/ui/map.html into a TypeScript module (src/ui/map-html.ts) so the
// HTML ships as a bundled string constant. This guarantees the UI resource is
// available at runtime in serverless environments (e.g. Vercel) without relying
// on filesystem reads. Run automatically via the "prebuild" npm script.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const html = readFileSync(join(root, 'src/ui/map.html'), 'utf-8');

const out = `// AUTO-GENERATED by scripts/inline-ui.mjs — do not edit by hand.
// Source: src/ui/map.html
export const MAP_HTML: string = ${JSON.stringify(html)};
`;

writeFileSync(join(root, 'src/ui/map-html.ts'), out, 'utf-8');
console.log(`inline-ui: wrote src/ui/map-html.ts (${html.length} bytes of HTML)`);
