// Builds a fully SELF-CONTAINED version of src/ui/map.html and writes it to
// src/ui/map-html.ts as a string constant. MCP App hosts render UI resources in
// a locked-down sandboxed iframe where external <script>/<link>/import() loads
// are unreliable, so we inline everything:
//   - Leaflet + MarkerCluster CSS/JS (from node_modules)
//   - The MCP App bridge (esbuild-bundled from src/ui/bridge-entry.js)
// Only map tile images remain external (declared via CSP in the tool).
// Also regenerates preview/index.html (self-contained + baked sample data) so
// the local preview matches production exactly.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { buildSync } from 'esbuild';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const nm = join(root, 'node_modules');

function read(p) {
  return readFileSync(p, 'utf-8');
}

// 1. Inline Leaflet + MarkerCluster CSS.
const leafletCss = [
  read(join(nm, 'leaflet/dist/leaflet.css')),
  read(join(nm, 'leaflet.markercluster/dist/MarkerCluster.css')),
  read(join(nm, 'leaflet.markercluster/dist/MarkerCluster.Default.css')),
].join('\n');

// 2. Inline Leaflet + MarkerCluster JS (order matters: Leaflet first).
const leafletJs = [
  read(join(nm, 'leaflet/dist/leaflet.js')),
  read(join(nm, 'leaflet.markercluster/dist/leaflet.markercluster.js')),
].join('\n;\n');

// 3. Bundle the MCP App bridge into a single browser IIFE (no external loads).
const bridge = buildSync({
  entryPoints: [join(root, 'src/ui/bridge-entry.js')],
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: 'es2020',
  minify: true,
  write: false,
});
const bridgeJs = bridge.outputFiles[0].text;

// 4. Assemble the self-contained HTML from the template placeholders.
const template = read(join(root, 'src/ui/map.html'));
// Use FUNCTION replacements so `$` sequences in minified JS/CSS are inserted
// literally (string replacements interpret $&, $`, $' and would corrupt output).
const html = template
  .replace('<!--__LEAFLET_CSS__-->', () => `<style>\n${leafletCss}\n</style>`)
  .replace('<!--__LEAFLET_JS__-->', () => `<script>\n${leafletJs}\n</script>`)
  .replace('<!--__BRIDGE_JS__-->', () => `<script>\n${bridgeJs}\n</script>`);

if (html.includes('unpkg.com') || html.includes('esm.sh')) {
  throw new Error('inline-ui: external CDN reference still present after inlining');
}

const out = `// AUTO-GENERATED by scripts/inline-ui.mjs — do not edit by hand.
// Source: src/ui/map.html (with Leaflet + MCP App bridge inlined)
export const MAP_HTML: string = ${JSON.stringify(html)};
`;
writeFileSync(join(root, 'src/ui/map-html.ts'), out, 'utf-8');

// 5. Regenerate the local preview (self-contained HTML + baked sample data).
const sampleData = join(root, 'preview/sample-data.js');
if (existsSync(sampleData)) {
  const previewHtml = html.replace(
    '</head>',
    `<script>\n${read(sampleData)}\n</script>\n</head>`
  );
  writeFileSync(join(root, 'preview/index.html'), previewHtml, 'utf-8');
}

console.log(
  `inline-ui: wrote src/ui/map-html.ts (${(html.length / 1024).toFixed(0)} KB, self-contained; ` +
    `bridge ${(bridgeJs.length / 1024).toFixed(0)} KB, leaflet ${(leafletJs.length / 1024).toFixed(0)} KB)`
);
